AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Front hosting (S3 private + CloudFront OAC) for legacy multi-page HTML + Vue(Vite) under /csv/
  and reverse proxy /api/* to API Gateway REST API stage (/prod) under the SAME domain.

Parameters:
  ProjectName:
    Type: String
    Default: front-app

  BucketName:
    Type: String
    Default: ""
    Description: Optional. If empty, CloudFormation will generate a bucket name.

  PriceClass:
    Type: String
    Default: PriceClass_200
    AllowedValues: [PriceClass_100, PriceClass_200, PriceClass_All]

  CustomDomainName:
    Type: String
    Default: ""
    Description: Optional. e.g. app.example.com (leave empty to skip)

  AcmCertificateArnUsEast1:
    Type: String
    Default: ""
    Description: Optional. ACM cert ARN in us-east-1 for CloudFront (leave empty to skip)

  # --- API Gateway REST execute-api domain + stage ---
  ApiGatewayDomainName:
    Type: String
    Description: "Example: abcdef123.execute-api.ap-northeast-3.amazonaws.com"

  ApiStageName:
    Type: String
    Default: prod
    Description: "REST API stage name (e.g. prod). Required in your case."

  # Auth style (Cookie forward)
  ForwardCookiesToApi:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: "true: forward all cookies to API (cookie session). false: do not forward cookies (JWT etc)."

Conditions:
  BucketNameProvided: !Not [!Equals [!Ref BucketName, ""]]
  UseCustomDomain: !And
    - !Not [!Equals [!Ref CustomDomainName, ""]]
    - !Not [!Equals [!Ref AcmCertificateArnUsEast1, ""]]
  UseCookieForwarding: !Equals [!Ref ForwardCookiesToApi, "true"]

Resources:
  # -------------------
  # S3 (private)
  # -------------------
  FrontBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [BucketNameProvided, !Ref BucketName, !Ref "AWS::NoValue"]
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # -------------------
  # CloudFront OAC
  # -------------------
  FrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # -------------------
  # Security Headers
  # -------------------
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${ProjectName}-security-headers"
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: no-referrer
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true

  CachePolicyStaticLong:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${ProjectName}-static-long"
        DefaultTTL: 31536000
        MaxTTL: 31536000
        MinTTL: 86400
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # -------------------
  # CloudFront Function: /csv/* only SPA fallback
  # -------------------
  CsvSpaFallbackFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${ProjectName}-csv-spa-fallback"
      AutoPublish: true
      FunctionConfig:
        Comment: Rewrite /csv routes (no extension) to /csv/index.html
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          if (uri === "/csv") {
            request.uri = "/csv/";
            return request;
          }

          if (uri === "/csv/") {
            request.uri = "/csv/index.html";
            return request;
          }

          if (uri.startsWith("/csv/")) {
            var last = uri.split("/").pop();

            // has extension => assets/js/css/img/etc
            if (last.indexOf(".") !== -1) {
              return request;
            }

            request.uri = "/csv/index.html";
            return request;
          }

          return request;
        }

  # -------------------
  # CloudFront Distribution
  # -------------------
  FrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "${ProjectName} legacy multi-page + Vue under /csv + REST API under /api (stage /${ApiStageName})"
        DefaultRootObject: index.html
        PriceClass: !Ref PriceClass
        HttpVersion: http2and3

        Origins:
          # S3 origin (static)
          - Id: s3origin
            DomainName: !GetAtt FrontBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref FrontOAC

          # API Gateway REST origin
          - Id: apigworigin
            DomainName: !Ref ApiGatewayDomainName
            OriginPath: !Sub "/${ApiStageName}" # required: /prod
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPPort: 80
              HTTPSPort: 443
              OriginSSLProtocols: [TLSv1.2]

        # ★重要：全体SPAではないので、403/404 を /index.html に寄せない
        CustomErrorResponses: []

        DefaultCacheBehavior:
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled

        CacheBehaviors:
          # 1) API reverse proxy: /api/* -> API Gateway (/prod/api/*)
          - PathPattern: /api/*
            TargetOriginId: apigworigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD, OPTIONS]
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac

          # 2) Vue assets long cache
          - PathPattern: /csv/assets/*
            TargetOriginId: s3origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD, OPTIONS]
            Compress: true
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            CachePolicyId: !Ref CachePolicyStaticLong

          # 3) Vue /csv/* SPA fallback by Function
          - PathPattern: /csv/*
            TargetOriginId: s3origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD, OPTIONS]
            Compress: true
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
            FunctionAssociations:
              - EventType: viewer-request
                FunctionARN: !GetAtt CsvSpaFallbackFunction.FunctionARN

        ViewerCertificate: !If
          - UseCustomDomain
          - AcmCertificateArn: !Ref AcmCertificateArnUsEast1
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

        Aliases: !If
          - UseCustomDomain
          - [!Ref CustomDomainName]
          - !Ref "AWS::NoValue"

  # -------------------
  # S3 Bucket Policy: allow CloudFront OAC read
  # -------------------
  FrontBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: [s3:GetObject]
            Resource: !Sub "arn:aws:s3:::${FrontBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontDistribution}"

Outputs:
  BucketName:
    Value: !Ref FrontBucket
    Description: Upload legacy HTML to root and Vue dist to s3://bucket/csv/

  CloudFrontDomainName:
    Value: !GetAtt FrontDistribution.DomainName
    Description: Access your app via this CloudFront domain

  CloudFrontDistributionId:
    Value: !Ref FrontDistribution
    Description: Use this for invalidations
